### ISSUE TITLE
Unable to locate file

### ISSUE THREAD

**Issue by maghams** [TheEconomist/us-potus-model#13]
Hi, I keep receiving the following error on line 250 and am unsure on how to resolve it as I cannot locate the "historical_prior_simulations.rds" file in the data folder.

Error:
In gzfile(file, "rb") :
  cannot open compressed file 'data/historical_prior_simulations.rds', probable reason 'No such file or directory'

Thank you!

**Comment by elliottmorris** [comment]
Not in the code anymore. Shouldn't need it.
