### ISSUE TITLE
2008 polls

### ISSUE THREAD

**Issue by zmeers** [TheEconomist/us-potus-model#14]
Hi,

Just wanted to double check that the polls in 2008 are prior to the election or do they cover the post-election period as well?

There are some polls that fall in December 2008. I just want to make sure this isn't a typo.

An example is below:

-- | CNN | 1019 | 12/15/08 | 12/17/08 | 43 | 47 | 7 | 3 | Live Phone | Registered Voters

**EDIT:** I just double checked RCP (https://www.realclearpolitics.com/epolls/2008/president/us/general_election_mccain_vs_obama-225.html#polls), looks like some 2008 polls were conducted in 2007, so in your data some of the national polls have the wrong year.

Thanks,
Zoe

**Comment by elliottmorris** [comment]
Zoe,

Some of the 2008 and 2012 polls have errors in the original data source that we neglected to correct. This appears to be one of them. The phone mode and population variables are also randomly generated, and as such we created separate models to ignore them. in testing.

We should have collected these data (and more) a bit more properly. But as they're not used for any parameter-tuning or model calibration, it wasn't worth our limited time to fix.

We will add a disclaimer to the readme to this end.

Elliott
