### ISSUE TITLE
Unused parameter in stan model

### ISSUE THREAD

**Issue by nesanders** [TheEconomist/us-potus-model#17]
It looks like all references to the `mu_b_T_model_estimation_error` parameter are commented out in the `poll_model_2020.stan` model as well as `poll_model_2020_no_mode_adjustment.stan`.  Presumably this variable should be removed from the parameters declaration.  I'm not sure if this is the current Stan behavior, but there are at least [some cases from past versions ](https://discourse.mc-stan.org/t/adding-unused-variable-changes-model-behaviour-answered-no-bug/8545) where unused parameters can negatively impact model behavior through unintended impacts on the posterior.

https://github.com/TheEconomist/us-potus-model/blob/85be55ae7b0bc68cb155a9ca975e155837eb4851/scripts/model/poll_model_2020.stan#L68

**Comment by elliottmorris** [comment]
fixed and closing
