### ISSUE TITLE
Extra levels in factor for population variable

### ISSUE THREAD

**Issue by balexanderstats** [TheEconomist/us-potus-model#19]
I'm not quite sure what model you use to adjust for pollster and mode effects. But I noticed that the population variable in your data set has the following levels:
"a", "rv", "lv", "rv ", "lv ". 
Meaning there are some polls where the population had an extra space. You can't see this but it appears when you run:
levels(data$population). Where data is the data frame of the polling data.
Here are the affected polls:
    state             pollster   sponsor start.date   end.date entry.date.time..et. number.of.observations population
374    --               YouGov Economist 2020-08-30 2020-09-01     9/2/2020 8:00:00                   1207        rv 
448    NH Saint Anselm College           2020-08-15 2020-08-17   8/20/2020 19:21:00                   1042        rv 
      mode biden trump biden_margin other undecided
374 Online    51    40           11     2         4
448 Online    51    43            8    NA        NA
                                                                                     url include notes 
374                                                             https://today.yougov.com    TRUE            63 days
448 https://htv-prod-media.s3.amazonaws.com/files/saintanselmpollaugust20-1597956431.pdf    TRUE      

    state                     pollster sponsor start.date   end.date entry.date.time..et. number.of.observations
662    -- Redfield & Wilton Strategies         2020-07-09 2020-07-09   7/13/2020 14:23:00                   1853
    population   mode biden trump biden_margin other undecided
662        lv  Online    48    40            8     3        10
                                                                            url include notes 
662 https://redfieldandwiltonstrategies.com/latest-usa-voting-intention-july-9/    TRUE

**Comment by elliottmorris** [comment]
Hi @balexanderstats,

This is a good catch. Thank you for sending the note. I believe I have fixed the issue with a handy find + replace, but let me know if you're still getting it. I will add an update to the code later to deal with this and #17.

E
