### ISSUE TITLE
Backtesting Results

### ISSUE THREAD

**Issue by balexanderstats** [TheEconomist/us-potus-model#27]
Would it be possible to provide a file with the model output from the 2008-2016 backtests? I know I could just run the files myself but that would be time-consuming. It would be helpful if people could see the backtesting results to better compare this model to others.

**Comment by elliottmorris** [comment]
There is a summary of 2008-2016 output in readme.md. What else are you looking for?

**Comment by balexanderstats** [comment]
I did not see that. That will be sufficient.
