### ISSUE TITLE
Potential use of 2016 election results in 2016 election?

### ISSUE THREAD

**Issue by simon-morris** [TheEconomist/us-potus-model#4]
I'm not super confident I'm fully understanding the logic which is going into state_data / state_cov / state_correlation, however it seems like the lines:

`state_data <- read.csv("data/potus_results_76_16.csv")
state_data <- state_data %>% 
  select(year, state, dem) %>%
  group_by(state) %>%
  mutate(dem = dem ) %>% #mutate(dem = dem - lag(dem)) %>%
  select(state,variable=year,value=dem)  %>%
  ungroup() %>%
  na.omit() %>%
  filter(variable == 2016)` 

(lines 99-107) in final_2016.R

Mean we use the 2016 election results to create these correlations. I would assume we'd want to use the 2012 results as our prior?

Related to this, is there a file for recreating the 2020 results? Or should I modify final_2016 for 2020?

**Comment by elliottmorris** [comment]
Hi Simon,

Thanks for your comment. Yes, this appears to be residual code from our 2020 model. You can swap the years out as you note (set `variable == 2012` in the `filter()` function). 

I will be very, very surprised if this changes the model, however; the correlations across the other demographic variables tend to overpower changes to any single one of them.

**Comment by simon-morris** [comment]
Yeah, that was my understanding too, but I wanted to make sure I understood what it was doing.

**Comment by elliottmorris** [comment]
Great. 

As far as replicating for 2020, we won't be publishing the precise prior we are using until after the election. But you can closely approximate  it by removing the lines reading in the priors for 2008, 2012 and 2016 and just use the linear model based on quarter 2 GDP growth and presidential approval.

**Comment by simon-morris** [comment]
Can you explain a little bit about why you use such a different prior for 2020 than to previous elections? I don't think I follow

**Comment by elliottmorris** [comment]
We use the same prior, we just haven’t saved the output for 2020 (or the script that could create it) to this repo.

**Comment by simon-morris** [comment]
Gotcha, I don't quite understand the method for creating the prior yet, which is why I didn't recognise it.
