### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by william3031** [TheEconomist/us-potus-model#5]
This is great. Are there files missing though?

e.g. `out  <- read_rds(sprintf('models/backtest_2008/stan_model_%s.rds',RUN_DATE))`

> cannot open compressed file 'models/backtest_2008/stan_model_2008-11-03.rds', probable reason 'No such file or directory'Error in gzfile(file, "rb") : cannot open the connection

**Comment by elliottmorris** [comment]
Yes, the model files are not uploaded as they are far too big for github. You’ll have to run the corresponding R scripts for each election in order to knit the overall .Rmd report.

**Comment by william3031** [comment]
Great. Thanks for your response.
