### ISSUE TITLE
Thank you for opensource the code, a quick question

### ISSUE THREAD

**Issue by Paul-Yuchao-Dong** [TheEconomist/us-potus-model#6]
Really grateful you guys had shared this. Such an audacious attempt to forecast something so uncertain into the future.

Just to confirm, after reading the "How it works" document explaining the methodology I am trying to locate the corresponding code that generated the beta prior for the popular vote, but could find any.

Maybe it's down to my limited understanding of stan, but I really didn't see any elastic net code either.

Bests,
Paul

**Comment by elliottmorris** [comment]
We haven't made the beta regression for the prior available yet. Thanks Paul. E

**Comment by Paul-Yuchao-Dong** [comment]
thank you for sharing!
