### ISSUE TITLE
Incorrect data in poll sheet

### ISSUE THREAD

**Issue by nicholasbaileyrally** [TheEconomist/us-potus-model#8]
Hi there. 

I noticed today that the downloadable sheet you have of current polling data on the economist website has incorrect values for the Biden vote share on the latest RMG poll. That poll has a 46% vote share for Biden, not the 48% in your data. I don't know how much that will adjust your model - I assume mostly a wiggle since it's one poll, but wanted to alert you to the error.

If this is a deliberate adjustment to weight a partisan poll or something, ignore this issue!

**Comment by elliottmorris** [comment]
Thank you. Issue resolved.

**Comment by nicholasbaileyrally** [comment]
No thank you for your awesome modeling work!

**Comment by tomsc87** [comment]
Similar problem with the latest Redfield & Wilton poll. Trump got 40% (not 39%) (meaning also that undecided/don't know was 8%, not 9%), there were 2,000 respondents (not 1,853), and the respondents were registered voters (not likely voters).

**Comment by elliottmorris** [comment]
We must be looking at different toplines then.

**Comment by tomsc87** [comment]
I'm looking at the source you provided. Nowhere on the Redfield & Wilton page does it mention 1,853 (with or without the thousands separator).

![Source](https://user-images.githubusercontent.com/42043874/87445768-5cebc680-c5f0-11ea-981f-d0850f5634bf.png)
![Report](https://user-images.githubusercontent.com/42043874/87446267-fdda8180-c5f0-11ea-81f7-3245d25b75cc.png)

**Comment by elliottmorris** [comment]
That may be my fault. I think their full numbers (with Kanye West) are at a different link. https://twitter.com/ppollingnumbers/status/1282768444484734978?s=21
